FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:f5d2c6a1e0c86e4234ea601552dbabb4ced0e013a1efcbfb439f1f6a7a9275b0

LABEL description="Netcat is a computer networking utility for reading from and writing to network connections using TCP or UDP."
LABEL io.k8s.description="netcat is a computer networking utility for reading from and writing to network connections using TCP or UDP."
LABEL io.k8s.display-name="trillian_netcat"
LABEL io.openshift.tags="trillian netcat trusted-signer"
LABEL summary="Provides the trillian netcat binary for running trillian netcat"

RUN microdnf -y install nc
