FROM registry.redhat.io/rhel9/redis-6@sha256:f66a969319b7b106ce3928e674e27fb14299d225d79c91cb51ab2a91f5e815a8

LABEL description="Securesign redis is built ontop of rhel9/redis-6 but accepts external connections and runs appendonly mode with full durability."
LABEL io.k8s.description="Securesign redis is built ontop of rhel9/redis-6 but accepts external connections and runs appendonly mode with full durability."
LABEL io.k8s.display-name="redis container image for Red Hat trusted artifact signer."
LABEL io.openshift.tags="redis, Red Hat trusted artifact signer."
LABEL summary="Runs redis in appendonly mode with enablement for external connections by default."
LABEL com.redhat.component="redis"

USER 1001
#
RUN sed -i 's/#bind 127.0.0.1 -::1/bind 0.0.0.0/g' /etc/redis/redis.conf && sed -i 's/appendonly no/appendonly yes/g' /etc/redis/redis.conf

ENTRYPOINT ["container-entrypoint"]
CMD ["run-redis"]
