FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:82fad27b91361473d919522a01a1198f327230bf8d2b569a8995bdcd6ac7cb94

LABEL description="Netcat is a computer networking utility for reading from and writing to network connections using TCP or UDP."
LABEL io.k8s.description="netcat is a computer networking utility for reading from and writing to network connections using TCP or UDP."
LABEL io.k8s.display-name="trillian_netcat"
LABEL io.openshift.tags="trillian netcat trusted-signer"
LABEL summary="Provides the trillian netcat binary for running trillian netcat"

RUN microdnf -y install nc
