kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: Snapshot-Query
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: 'token'
      name: GH_TOKEN
      type: string
    - description: 'account'
      name: GITHUB_USER_NAME
      default: ""
      type: string
    - description: 'EMAIL'
      name: GITHUB_USER_EMAIL
      default: ""
      type: string
    - description: 'file to update'
      name: FILE_TO_UPDATE
      default: ""
      type: string
  tasks:
    - name: task-1
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: LABEL
          value: $(context.pipelineRun.name)
        - name: GH_TOKEN
          value: $(params.GH_TOKEN)
        - name: GITHUB_USER_NAME
          value: $(params.GITHUB_USER_NAME)
        - name: GITHUB_USER_EMAIL
          value: $(params.GITHUB_USER_EMAIL)
        - name: FILE_TO_UPDATE
          value: $(params.FILE_TO_UPDATE) 
      taskSpec:
        params:
        - name: SNAPSHOT
        - name: GH_TOKEN
        - name: GITHUB_USER_EMAIL
        - name: GITHUB_USER_NAME
        - name: FILE_TO_UPDATE
        results:
        - name: TEST_OUTPUT
          description: Test output
        steps:
        - image: registry.redhat.io/openshift4/ose-cli@sha256:4257542c6e7343abd048f8b1c1e06afeed8d4e4bfafe8621fcfa32b92c77b644
          env:
          - name: SNAPSHOT
            value: $(params.SNAPSHOT)
          - name: LABEL
            value: $(context.pipelineRun.name)
          - name: GH_TOKEN
            value: $(params.GH_TOKEN)
          - name: GITHUB_USER_EMAIL
            value: $(params.GITHUB_USER_EMAIL)
          - name: GITHUB_USER_NAME
            value: $(params.GITHUB_USER_NAME)
          - name: CHECK_RUN_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['pac.test.appstudio.openshift.io/check-run-id']
          - name: FILE_TO_UPDATE
            value: $(params.FILE_TO_UPDATE)
          script: |
            max_checks=30
            sleep_interval=10


            update_files()
            {
              git config --global user.email "${GITHUB_USER_EMAIL}"
              git config --global user.name "${GITHUB_USER_NAME}"
              git clone https://ret:${GH_TOKEN}@github.com/tommyd450/trillian.git
              cd trillian
              git remote -v
              git fetch origin
              git checkout trilltest
              echo "Updated" >> release.yaml
              ls -a
              git remote -v
              git add release.yaml
              git commit -m "Updating"
              git status
              git push origin trilltest:trilltest -f
            }

            check_ec_status(){
              local attempts=0

              while [[ $attempts -lt $max_attempts ]]; do
                EC_POD = oc --kubeconfig kubeconfig-rhtas.yaml get pods -l pac.test.appstudio.openshift.io/check-run-id=${CHECK_RUN_ID} | awk '{if (($3 ~ "Completed")&&($1 ~ "verify-pod")) print $1}'
                if [-z "$EC_POD"]; then
                  EC_STATUS = $(oc get pod "$EC_POD" -o jsonpath='{.status.phase}')
                  if [ ${EC_STATUS} == "Succeeded"]; then
                    return 0
                  else
                    echo "$EC_POD is in state: $EC_STATUS. Retrying in $sleep_interval seconds..."
                  fi
                else
                  echo "No verify pods running sleeping and checking again"
                fi

                sleep $sleep_interval
                attempts=$((attempts+1))
              done
              return 1
            }


            snapshot_fetcher(){
              dnf install -y gh
              check_ec_status()
              if [ $? -ne 0 ]; then
                  echo "Pod status check failed. Exiting the script."
                  exit 1
              fi

              update_files()
            }
       
            echo -e "Example test task for the Snapshot:\n ${SNAPSHOT}"
            echo -e "Test label: \n ${LABEL}"
            echo -e "TEST ID \n ${CHECK_RUN_ID}"
            echo -e "Token: \n ${GH_TOKEN}"
            jq ${SNAPSHOT}
            // Run custom tests for the given Snapshot here
            // After the tests finish, record the overall result in the RESULT variable
            
            RESULT="$LABEL"
            // Output the standardized TEST_OUTPUT result in JSON form
            TEST_OUTPUT=$(jq -rc --arg date $(date +%s) --arg RESULT "${RESULT}" --null-input \
              '{result: $RESULT, timestamp: $date, failures: 0, successes: 1, warnings: 0}')
            echo -n "${TEST_OUTPUT}" | tee $(results.TEST_OUTPUT.path)