kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: Snapshot-Query
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: 'token'
      name: TOKEN
      type: string
    - description: 'account'
      name: GITHUB_USER_NAME
      default: ""
      type: string
    - description: 'EMAIL'
      name: GITHUB_USER_EMAIL
      default: ""
      type: string
  tasks:
    - name: task-1
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: LABEL
          value: $(context.pipelineRun.name)
        - name: TOKEN
          value: $(params.TOKEN)
        - name: GITHUB_USER_NAME
          value: $(params.GITHUB_USER_NAME)
        - name: GITHUB_USER_EMAIL
          value: $(params.GITHUB_USER_EMAIL)
      taskSpec:
        params:
        - name: SNAPSHOT
        - name: TOKEN
        - name: GITHUB_USER_EMAIL
        - name: GITHUB_USER_NAME
        results:
        - name: TEST_OUTPUT
          description: Test output
        steps:
        - image: registry.access.redhat.com/ubi9/go-toolset@sha256:ace149b17c62803c8a4d3ecfbc0c17dd9a4242ea3f0a6f14a4578474e34c3c3e
          env:
          - name: SNAPSHOT
            value: $(params.SNAPSHOT)
          - name: LABEL
            value: $(context.pipelineRun.name)
          - name: TOKEN
            value: $(params.TOKEN)
          - name: GITHUB_USER_EMAIL
            value: $(params.GITHUB_USER_EMAIL)
          - name: GITHUB_USER_NAME
            value: $(params.GITHUB_USER_NAME)
          script: |
            pwd
            ls -a
            git config --global user.email "${GITHUB_USER_EMAIL}"
            git config --global user.name "${GITHUB_USER_NAME}"
            git clone https://${TOKEN}@github.com:tommyd450/trillian.git
            ls -a
            cd trillian
            ls -a
            cat << EOF > ./release.yaml
            test
            EOF
            git add release.yaml
            git commit -m "Updating"
            git push https://${TOKEN}@github.com/tommyd450/trillian.git trilltest

            echo -e "Example test task for the Snapshot:\n ${SNAPSHOT}"
            echo -e "Test label: \n ${LABEL}"
            echo -e "Token: \n ${TOKEN}"
            // Run custom tests for the given Snapshot here
            // After the tests finish, record the overall result in the RESULT variable
            
            RESULT="$LABEL"
            // Output the standardized TEST_OUTPUT result in JSON form
            TEST_OUTPUT=$(jq -rc --arg date $(date +%s) --arg RESULT "${RESULT}" --null-input \
              '{result: $RESULT, timestamp: $date, failures: 0, successes: 1, warnings: 0}')
            echo -n "${TEST_OUTPUT}" | tee $(results.TEST_OUTPUT.path)