kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: Snapshot-Query
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: 'token'
      name: TOKEN
      type: string
    - description: 'account'
      name: GITHUB_USER_NAME
      default: ""
      type: string
    - description: 'EMAIL'
      name: GITHUB_USER_EMAIL
      default: ""
      type: string
    - description: 'file to update'
      name: FILE_TO_UPDATE
      default: ""
      type: string
  tasks:
    - name: task-1
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: LABEL
          value: $(context.pipelineRun.name)
        - name: TOKEN
          value: $(params.TOKEN)
        - name: GITHUB_USER_NAME
          value: $(params.GITHUB_USER_NAME)
        - name: GITHUB_USER_EMAIL
          value: $(params.GITHUB_USER_EMAIL)
        - name: FILE_TO_UPDATE
          value: $(params.FILE_TO_UPDATE) 
      taskSpec:
        params:
        - name: SNAPSHOT
        - name: TOKEN
        - name: GITHUB_USER_EMAIL
        - name: GITHUB_USER_NAME
        - name: FILE_TO_UPDATE
        results:
        - name: TEST_OUTPUT
          description: Test output
        steps:
        - image: registry.redhat.io/openshift4/ose-cli@sha256:4257542c6e7343abd048f8b1c1e06afeed8d4e4bfafe8621fcfa32b92c77b644
          env:
          - name: SNAPSHOT
            value: $(params.SNAPSHOT)
          - name: LABEL
            value: $(context.pipelineRun.name)
          - name: TOKEN
            value: $(params.TOKEN)
          - name: GITHUB_USER_EMAIL
            value: $(params.GITHUB_USER_EMAIL)
          - name: GITHUB_USER_NAME
            value: $(params.GITHUB_USER_NAME)
          - name: CHECK_RUN_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['pac.test.appstudio.openshift.io/check-run-id']
          - name: FILE_TO_UPDATE
            value: $(params.FILE_TO_UPDATE)
          script: |
            dnf install -y gh
            pwd
            ls -a
            git config --global user.email "${GITHUB_USER_EMAIL}"
            git config --global user.name "${GITHUB_USER_NAME}"
            git clone https://ret:${TOKEN}@github.com/tommyd450/trillian.git
          
            cd trillian
            git remote -v
            git fetch origin
            git checkout trilltest
            cat << EOF > ./release.yaml
            test
            gh
            EOF
            ls -a
            git remote -v
            git add release.yaml
            git commit -m "Updating"
            git status
            git push origin trilltest:trilltest -f

            gh pr create 

            echo -e "Example test task for the Snapshot:\n ${SNAPSHOT}"
            echo -e "Test label: \n ${LABEL}"
            echo -e "TEST ID \n ${CHECK_RUN_ID}"
            echo -e "Token: \n ${TOKEN}"
            jq ${SNAPSHOT}
            // Run custom tests for the given Snapshot here
            // After the tests finish, record the overall result in the RESULT variable
            
            RESULT="$LABEL"
            // Output the standardized TEST_OUTPUT result in JSON form
            TEST_OUTPUT=$(jq -rc --arg date $(date +%s) --arg RESULT "${RESULT}" --null-input \
              '{result: $RESULT, timestamp: $date, failures: 0, successes: 1, warnings: 0}')
            echo -n "${TEST_OUTPUT}" | tee $(results.TEST_OUTPUT.path)