FROM registry.access.redhat.com/ubi9/go-toolset@sha256:6e199b7101e258e5c30124ede22f442de560b09e1b251dd3de32d4f45b9e15af AS builder
ENV APP_ROOT=/opt/app-root
ENV GOPATH=$APP_ROOT
ENV CGO_ENABLED=false
ENV -buildvcs=false

WORKDIR $APP_ROOT/src/
ADD go.mod go.sum $APP_ROOT/src/
RUN go mod download
RUN git config --global --add safe.directory /opt/app-root/src

# Add source code
ADD ./ $APP_ROOT/src/

RUN go build -v ./cmd/trillian_log_signer


# Multi-Stage production build
FROM registry.access.redhat.com/ubi9/go-toolset@sha256:6e199b7101e258e5c30124ede22f442de560b09e1b251dd3de32d4f45b9e15af as deploy

# Retrieve the binary from the previous stage
COPY --from=builder /opt/app-root/src/trillian_log_signer /

# Set the binary as the entrypoint of the container
ENTRYPOINT ["/trillian_log_signer"]